# Use node image as base image
FROM node:14

# Set working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to work directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all source code to work directory
COPY . .

# Expose port 8000
EXPOSE 8000

# Command to run the application
CMD ["node", "server.mjs"]
